# Generated by Django 4.2.6 on 2023-10-16 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_alter_user_cellphone_alter_user_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cashier.account'),
        ),
    ]
