# Generated by Django 4.2.6 on 2023-10-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=999999.99),
        ),
    ]
